{{- if and .Values.vault.basePath .Values.fcm.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "rb-stack.fullname" . }}-fcm-secret
  namespace: {{ include "rb-stack.namespace" . }}
  labels:
    {{- include "rb-stack.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.vault.refreshInterval | default "30s" }}
  secretStoreRef:
    name: {{ include "rb-stack.secretStoreName" . }}
    kind: SecretStore
  target:
    name: {{ include "rb-stack.fullname" . }}-fcm-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.vault.basePath }}/{{ .Values.environment }}/fcm
{{- end }}
